package tech.xirius.tutorial.filter.entities;

@AutoFilter
@Entity
public class User {
    @AutoFilterExclude
    private Region userRegion;
    private String username;
    private Boolean active;
    @AutoFilterInclude(baseFilter = CustomFilter.class)
    private int strikes;
    /* Note that we can use a filter generated by @AutoFilter as 
    baseFilter but you MUST avoid cyclical references
    */
    @AutoFilterInclude(baseFilter = PersonFilter.class)
    private Person realPerson;
}

