package tech.xirius.tutorial.filter.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

import lombok.Getter;
import lombok.Setter;
import tech.xirius.filter.auto.annotations.AutoFilter;
import tech.xirius.filter.auto.annotations.AutoFilterExclude;
import tech.xirius.filter.auto.annotations.AutoFilterInclude;
import tech.xirius.filter.filtering.RangeFilter;
import tech.xirius.tutorial.filter.services.filter.NameFilter;

@Getter
@Setter
@AutoFilter
@Entity
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @AutoFilterExclude
    private Region userRegion;
    @AutoFilterInclude(baseFilter = NameFilter.class)
    private String username;
    private Boolean active;
    @AutoFilterInclude(baseFilter = RangeFilter.class)
    private int strikes;
    /**
     * Note that we can use a filter generated by @AutoFilter as baseFilter but you MUST avoid cyclical references
     */
    @AutoFilterInclude(baseFilter = PersonFilter.class)
    @OneToOne
    private Person realPerson;
}

