#SPRING CONFIGURATION
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:testdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect